import { Message } from '../session/types.js';

/**
 * Formats a conversation into markdown format.
 */
export function formatMarkdown(
  conversation: string | Message[],
  topic: string,
  format: 'plain' | 'messages' = 'plain'
): string {
  const date = new Date().toISOString();
  const version = '0.1.3';

  let conversationText: string;

  if (format === 'messages' && Array.isArray(conversation)) {
    conversationText = formatMessages(conversation);
  } else {
    conversationText =
      typeof conversation === 'string' ? conversation : JSON.stringify(conversation, null, 2);
  }

  return `# ${topic}

**Date:** ${date}
**Type:** AI Conversation Session

---

## Conversation

${conversationText}

---

*Generated by CodeArchitect MCP v${version}*
`;
}

/**
 * Formats an array of messages into markdown.
 */
function formatMessages(messages: Message[]): string {
  return messages
    .map((msg) => {
      const role = msg.role || 'unknown';
      const content =
        typeof msg.content === 'string' ? msg.content : JSON.stringify(msg.content, null, 2);
      return `**${role.toUpperCase()}:**\n\n${content}`;
    })
    .join('\n\n---\n\n');
}
