import { formatMarkdown } from '../../src/store-session/markdown-formatter.js';

describe('MarkdownFormatting', () => {
  it('should format plain text conversation', () => {
    const conversation = 'User: Hello\nAI: Hi there!';
    const topic = 'test-session';
    const markdown = formatMarkdown(conversation, topic, 'plain');

    expect(markdown).toContain('# test-session');
    expect(markdown).toContain('**Date:**');
    expect(markdown).toContain('User: Hello');
    expect(markdown).toContain('AI: Hi there!');
    expect(markdown).toContain('Generated by CodeArchitect MCP');
  });

  it('should format messages array', () => {
    const conversation = [
      { role: 'user', content: 'Hello' },
      { role: 'assistant', content: 'Hi there!' },
    ];
    const topic = 'test-session';
    const markdown = formatMarkdown(conversation, topic, 'messages');

    expect(markdown).toContain('# test-session');
    expect(markdown).toContain('**USER:**');
    expect(markdown).toContain('**ASSISTANT:**');
    expect(markdown).toContain('Hello');
    expect(markdown).toContain('Hi there!');
  });

  it('should include metadata', () => {
    const conversation = 'test';
    const topic = 'test-session';
    const markdown = formatMarkdown(conversation, topic);

    expect(markdown).toContain('**Date:**');
    expect(markdown).toContain('**Type:** AI Conversation Session');
  });

  it('should handle empty conversation', () => {
    const conversation = '';
    const topic = 'empty-test';
    const markdown = formatMarkdown(conversation, topic);

    expect(markdown).toContain('# empty-test');
  });

  it('should handle messages with non-string content', () => {
    const conversation = [
      { role: 'user', content: { text: 'Hello' } },
    ];
    const topic = 'test';
    const markdown = formatMarkdown(conversation, topic, 'messages');

    expect(markdown).toContain('USER');
    expect(markdown).toContain('Hello');
  });
});

